apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-demo
  labels:
    app.kubernetes.io/name: tilt-demo
    app.kubernetes.io/version: 0.1.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tilt-demo
      app.kubernetes.io/version: 0.1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tilt-demo
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: tilt-demo
          image: tilt-demo
          ports:
            - containerPort: 8000
